# Generated by Django 4.0.1 on 2022-01-19 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_front', '0008_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
