# Generated by Django 4.0.1 on 2022-01-19 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('web_front', '0014_alter_advert_user_alter_advertsearch_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_children', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Silhouette',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_silhouette', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
