# Generated by Django 4.0.1 on 2022-01-19 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('web_front', '0015_children_silhouette'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tobacco',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_tobacco', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBirthDate',
            fields=[
                ('name', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_birth_date', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
