# Generated by Django 4.0.1 on 2022-01-19 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_front', '0019_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_visit_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visits',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_visit_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
