# Generated by Django 4.0.1 on 2022-01-19 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_front', '0021_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visits',
            old_name='user_from',
            new_name='user_visits_from',
        ),
        migrations.RenameField(
            model_name='visits',
            old_name='user_to',
            new_name='user_visits_to',
        ),
    ]
