# Generated by Django 4.0.1 on 2022-01-19 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_front', '0022_rename_user_from_visits_user_visits_from_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Children',
        ),
    ]
