# Generated by Django 4.0.1 on 2022-01-19 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_front', '0023_delete_children'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Silhouette',
        ),
    ]
