# Generated by Django 4.0.1 on 2022-01-19 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_front', '0024_delete_silhouette'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertsearch',
            name='user',
        ),
        migrations.RemoveField(
            model_name='disability',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gender',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hairs',
            name='user',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sexuality',
            name='user',
        ),
        migrations.RemoveField(
            model_name='size',
            name='user',
        ),
        migrations.RemoveField(
            model_name='status',
            name='user',
        ),
        migrations.DeleteModel(
            name='Advert',
        ),
        migrations.DeleteModel(
            name='AdvertSearch',
        ),
        migrations.DeleteModel(
            name='Disability',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='Hairs',
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
        migrations.DeleteModel(
            name='Sexuality',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
