# Generated by Django 4.0.1 on 2022-01-19 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_front', '0026_remove_eyes_user_remove_origins_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visits',
            name='user_visits_from',
        ),
        migrations.RemoveField(
            model_name='visits',
            name='user_visits_to',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='Visits',
        ),
    ]
