# Generated by Django 4.0.1 on 2022-01-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_front', '0027_remove_visits_user_visits_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='user',
        ),
        migrations.RemoveField(
            model_name='music',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tv',
            name='user',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Cinema',
        ),
        migrations.DeleteModel(
            name='Music',
        ),
        migrations.DeleteModel(
            name='Tv',
        ),
    ]
