# Generated by Django 4.0.1 on 2022-01-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_front', '0034_remove_profile_id_remove_profile_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
