# Generated by Django 4.0.1 on 2022-01-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_front', '0037_alter_location_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='asLocation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='isp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='org',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
