# Generated by Django 4.0.1 on 2022-01-22 06:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_front', '0042_profile_search_alter_profile_eyes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alcohol',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='search',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
