# Generated by Django 4.0.1 on 2022-01-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_front', '0044_profile_children_profile_silhouette_profile_tobacco'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='advert',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='advert_search',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='disability',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='hairs',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='relation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='sexuality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='size',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
