# Generated by Django 4.0.1 on 2022-01-22 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_front', '0047_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tv', to='web_front.profile'),
        ),
    ]
