# Generated by Django 4.0.1 on 2022-01-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_front', '0051_rename_user_location_user_alter_location_timezone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='User',
            new_name='user',
        ),
    ]
