# Generated by Django 4.0.1 on 2022-01-24 13:55

from django.db import migrations, models
import web_front


class Migration(migrations.Migration):

    dependencies = [
        ('web_front', '0054_remove_location_user_location_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[web_front.models.calculate_age]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
