# Generated by Django 4.0.1 on 2022-01-24 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_front', '0055_alter_profile_birth_date_alter_profile_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='size',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(120)]),
        ),
    ]
